services:
  - type: web
    name: blackedge
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GOOGLE_API_KEY
        sync: false
